name: Compile Devtools Frontend
on:
  workflow_dispatch:
    inputs: 
      purgenonenglishlocales: 
        type: boolean
        description: Remove Non-English locales
      purgejsmaps: 
        type: boolean
        description: Remove All JS Maps

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - name: Install Zip and Unzip
      run: sudo apt-get install -y zip unzip

    - name: Checkout Extra Directory
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          extra

    - name: Setup Pages Directory
      run: |
        mkdir $GITHUB_WORKSPACE/pages
        ls $GITHUB_WORKSPACE/pages

    - name: Download and Load Depot Tools
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git $GITHUB_WORKSPACE/depot_tools
        export PATH=$GITHUB_WORKSPACE/depot_tools:$PATH

    - name: Configure Username
      run: |
        git config --global user.name "Github Actions"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global core.autocrlf false
        git config --global core.filemode false
        git config --global color.ui true
    
    - name: Checkout devtools-frontend
      run: |
        export PATH=$GITHUB_WORKSPACE/depot_tools:$PATH
        cd $GITHUB_WORKSPACE
        mkdir devtools
        cd devtools
        fetch devtools-frontend

    - name: Build devtools-frontend
      run: |
        export PATH=$GITHUB_WORKSPACE/depot_tools:$PATH
        cd $GITHUB_WORKSPACE/devtools/devtools-frontend
        gclient sync
        gn gen out/Default --args='devtools_skip_typecheck=true'
        autoninja -C out/Default

    - name: Generate Unpatched ZIP
      run: |
        cd $GITHUB_WORKSPACE/devtools/devtools-frontend/out/Default/gen/front_end
        zip -9qrX $GITHUB_WORKSPACE/devtools-frontend-full.zip *

    - name: Purge Unnecessary Assets
      run: |
        cd $GITHUB_WORKSPACE/devtools/devtools-frontend/out/Default/gen/front_end
        rm -rf ./testing ./legacy_test_runner ./tests.txt
        rm -rf ./panels/timeline/fixtures/traces/*
        rm -rf $(find ./ -type f -name "*.test.js*")
        rm -rf $(find ./ -type f -name "*tsconfig.json")

    - name: Copy Files to Pages
      run: |
        cp -r $GITHUB_WORKSPACE/devtools/devtools-frontend/out/Default/gen/front_end/* $GITHUB_WORKSPACE/pages
        cp -r $GITHUB_WORKSPACE/extra $GITHUB_WORKSPACE/pages/extra
        cd $GITHUB_WORKSPACE/pages/extra && node ./_run.js

    - name: Publish to Cloudflare Pages
      uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: devtools-frontend
        directory: ${{ github.workspace }}/pages
        # Enable Wrangler v3
        wranglerVersion: '3'

    - name: Purge All JS Maps
      if: "${{ github.event.inputs.purgejsmaps == 'true' && github.event.inputs.purgejsmaps }}"
      run: |
        rm -rf $(find ./ -type f -name "*.map")

    - name: Purge Non-English Locales
      if: "${{ github.event.inputs.purgenonenglishlocales == 'true' && github.event.inputs.purgenonenglishlocales }}"
      run: |
        cd $GITHUB_WORKSPACE/devtools/devtools-frontend/out/Default/gen/front_end/core/i18n/locales
        rm -rf $(ls --hide='en*')

    - name: Generate ZIP for Release
      id: gen-zip
      run: |
        cd $GITHUB_WORKSPACE/devtools/devtools-frontend/out/Default/gen/front_end
        zip -9qrX $GITHUB_WORKSPACE/devtools-frontend.zip *
        echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Publish Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DevtoolsFrontend
        path: ${{ github.workspace }}/devtools/devtools-frontend/out/Default/gen/front_end

    - name: Publish Release
      id: publish_release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        make_latest: true
        tag_name: ${{ steps.gen-zip.outputs.SHA_SHORT }}
        name: Release ${{ steps.gen-zip.outputs.SHA_SHORT }}
        body: "Build Type:\nEnglish Only: ${{ github.event.inputs.purgenonenglishlocales || 'false' }}\nRemove JS Maps: ${{ github.event.inputs.purgejsmaps || 'false' }}\n\nIf you want the full bundle, download the devtools-frontend-full.zip from the asset list."
        draft: false
        prerelease: false
        files: |
          ${{ github.workspace }}/devtools-frontend.zip
          ${{ github.workspace }}/devtools-frontend-full.zip
