name: Compile Devtools Frontend
on:
  workflow_dispatch:
    inputs: 
      purgenonenglishlocales: 
        type: boolean
        description: Remove Non-English locales

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - name: Install Zip and Unzip
      run: sudo apt-get install -y zip unzip

    - name: Download and Load Depot Tools
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git $GITHUB_WORKSPACE/depot_tools
        export PATH=$GITHUB_WORKSPACE/depot_tools:$PATH

    - name: Configure Username
      run: |
        git config --global user.name "Github Actions"
        git config --global user.email "github-actions@github.com"
        git config --global core.autocrlf false
        git config --global core.filemode false
        git config --global color.ui true
    
    - name: Checkout devtools-frontend
      run: |
        export PATH=$GITHUB_WORKSPACE/depot_tools:$PATH
        cd $GITHUB_WORKSPACE
        mkdir devtools
        cd devtools
        fetch devtools-frontend

    - name: Build devtools-frontend
      run: |
        export PATH=$GITHUB_WORKSPACE/depot_tools:$PATH
        cd $GITHUB_WORKSPACE/devtools/devtools-frontend
        gclient sync
        gn gen out/Default --args='devtools_skip_typecheck=true'
        autoninja -C out/Default

    - name: Purge Unnecessary Assets
      run: |
        cd $GITHUB_WORKSPACE/devtools/devtools-frontend/out/Default/gen/front_end
        rm -rf ./testing ./legacy_test_runner
        rm -rf $(find ./ -type f -name "*.test.js*")
        rm -rf $(find ./ -type f -name "*tsconfig.json")

    - name: Purge Non-English Locales
      if: "${{ github.event.inputs.purgenonenglishlocales > '' && github.event.inputs.purgenonenglishlocales }}"
      run: |
        cd $GITHUB_WORKSPACE/devtools/devtools-frontend/out/Default/gen/front_end/core/i18n/locales
        rm -rf $(ls --hide='en*')

    - name: Generate ZIP for Release
      id: gen-zip
      run: |
        cd $GITHUB_WORKSPACE/devtools/devtools-frontend/out/Default/gen/front_end
        zip -9qrX $GITHUB_WORKSPACE/devtools-frontend.zip *
        echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Publish Artifact
      uses: actions/upload-artifact@v3
      with:
        name: DevtoolsFrontend
        path: ${{ github.workspace }}/devtools/devtools-frontend/out/Default/gen/front_end

    - name: Publish Release
      id: publish_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.gen-zip.outputs.SHA_SHORT }}
        release_name: Release ${{ steps.gen-zip.outputs.SHA_SHORT }}
        draft: false
        prerelease: false
    
    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.publish_release.outputs.upload_url }}
        asset_path: ${{ github.workspace }}/devtools-frontend.zip
        asset_name: devtools-frontend.zip
        asset_content_type: application/zip
